# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'ShoppingCar' do
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MJExtension'
  pod 'MBProgressHUD'

end
